### ISSUE TITLE
Add model loading progress bar

### ISSUE THREAD

**Issue by Randl** [wpmed92/yolov8-webgpu-tinygrad#1]
I get "Loading model" for quite a long time and I'm unsure whether something is stuck or I just need to wait more. Having some kind of progress bar would be helpful

**Comment by wpmed92** [comment]
If webgpu is not supported on your device it can stuck. The model loading consits of dowloading the model + compiling it. If it stucks, it probably because it fails compiling due to missing webgpu. I’ll update to report it on the ui if this happens

**Comment by wpmed92** [comment]
Can you check what do you get with the new deployement? You should see an error if webgpu is not available in your browser.

**Comment by Randl** [comment]
Yep, got it. Thanks!
